<?php

return [
    'fr' => [
        'home' => [
            [
                'title' => 'Pack Web Stater',
                'amount' => 1200,
                'unity' => 'Dh',
                'options' => [
                    '<li class="list-group-item">Hébergement</li>',
                    '<li class="list-group-item">Nom de domaine</li>',
                    '<li class="list-group-item">Thème responsive design</li>',
                    '<li class="list-group-item">Développement de 2 pages</li>',
                    '<li class="list-group-item">Rédaction de contenu</li>',
                    '<li class="list-group-item">Optimisation SEO</li>',
                    '<li class="list-group-item">Mise à jour du contenu</li>',
                    '<li class="list-group-item">Ajout de médias</li>',
                    '<li class="list-group-item">Maintenance du site</li>',
                    '<li class="list-group-item">Optimisation de contenu</li>',
                ],
                'url' => '',
            ],
            [
                'title' => 'Pack E-Com Mini',
                'amount' => 5500,
                'unity' => 'Dh',
                'options' => [
                    '<li class="list-group-item">Hébergement</li>',
                    '<li class="list-group-item">Nom de domaine</li>',
                    '<li class="list-group-item">Thème responsive design</li>',
                    '<li class="list-group-item">Développement de 4 pages</li>',
                    '<li class="list-group-item">Rédaction de contenu</li>',
                    '<li class="list-group-item">Optimisation SEO</li>',
                    '<li class="list-group-item">Mise à jour du contenu</li>',
                    '<li class="list-group-item">Ajout de médias</li>',
                    '<li class="list-group-item">Maintenance du site</li>',
                    '<li class="list-group-item">Optimisation de contenu</li>',
                ],
                'url' => '',
            ],
            [
                'title' => 'Pack Web Pro',
                'amount' => 3400,
                'unity' => 'Dh',
                'options' => [
                    '<li class="list-group-item">Hébergement</li>',
                    '<li class="list-group-item">Nom de domaine</li>',
                    '<li class="list-group-item">Thème responsive design</li>',
                    '<li class="list-group-item">Développement de 2 pages</li>',
                    '<li class="list-group-item">Rédaction de contenu</li>',
                    '<li class="list-group-item">Optimisation SEO</li>',
                    '<li class="list-group-item">Mise à jour du contenu</li>',
                    '<li class="list-group-item">Ajout de médias</li>',
                    '<li class="list-group-item">Maintenance du site</li>',
                    '<li class="list-group-item">Optimisation de contenu</li>',
                ],
                'url' => '',
            ],
        ],
        'prices' => [
            'showcase' => [
                [
                    'title' => 'Vitrine Starter',
                    'amount' => [
                        'ma' => 1500,
                        'ci' => 85000,
                        'other' => 150,
                    ],
                    'unity' => [
                        'ma' => 'Dh',
                        'ci' => 'f CFA',
                        'other' => '€',
                    ],
                    'options' => [
                        '<li class="list-group-item">Mise en forme d\'une single page</li>',
                        '<li class="list-group-item">Page de mentions légales</li>',
                        '<li class="list-group-item">1 formulaire de contact</li>',
                        '<li class="list-group-item">1 carte google si désirée</li>',
                    ],
                    'additional_options' => [
                        '<li class="list-group-item text-muted">Rédaction du contenu</li>',
                        '<li class="list-group-item text-muted">Mise à jour de votre contenu</li>',
                        '<li class="list-group-item text-muted">Ajout de langue</li>',
                        '<li class="list-group-item text-muted">Formulaire avancé (calendrier, demande de réservation, etc.)</li>',
                        '<li class="list-group-item text-muted">Autres fonctionalités sur étude</li>',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Vitrine Pro',
                    'amount' => [
                        'ma' => 3000,
                        'ci' => 170000,
                        'other' => 350,
                    ],
                    'unity' => [
                        'ma' => 'Dh',
                        'ci' => 'f CFA',
                        'other' => '€',
                    ],
                    'options' => [
                        '<li class="list-group-item">Mise en forme de 4 pages</li>',
                        '<li class="list-group-item">Page de mentions légales</li>',
                        '<li class="list-group-item">1 formulaire de contact</li>',
                        '<li class="list-group-item">1 carte google si désirée</li>',
                    ],
                    'additional_options' => [
                        '<li class="list-group-item text-muted">Rédaction du contenu</li>',
                        '<li class="list-group-item text-muted">Mise à jour de votre contenu</li>',
                        '<li class="list-group-item text-muted">Ajout de langue</li>',
                        '<li class="list-group-item text-muted">Formulaire avancé (calendrier, demande de réservation, etc.)</li>',
                        '<li class="list-group-item text-muted">Autres fonctionalités sur étude</li>',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Vitrine High',
                    'amount' => [
                        'ma' => 6000,
                        'ci' => 340000,
                        'other' => 700,
                    ],
                    'unity' => [
                        'ma' => 'Dh',
                        'ci' => 'f CFA',
                        'other' => '€',
                    ],
                    'options' => [
                        '<li class="list-group-item">Mise en forme de 10 pages</li>',
                        '<li class="list-group-item">Page de mentions légales</li>',
                        '<li class="list-group-item">1 formulaire de contact</li>',
                        '<li class="list-group-item">1 carte google si désirée</li>',
                    ],
                    'additional_options' => [
                        '<li class="list-group-item text-muted">Rédaction du contenu</li>',
                        '<li class="list-group-item text-muted">Mise à jour de votre contenu</li>',
                        '<li class="list-group-item text-muted">Ajout de langue</li>',
                        '<li class="list-group-item text-muted">Formulaire avancé (calendrier, demande de réservation, etc.)</li>',
                        '<li class="list-group-item text-muted">Autres fonctionalités sur étude</li>',
                    ],
                    'url' => '',
                ],
            ],
            'portfolio' => [
                [
                    'title' => 'Portfolio Starter',
                    'amount' => [
                        'ma' => 1800,
                        'ci' => 95000,
                        'other' => 180,
                    ],
                    'unity' => [
                        'ma' => 'Dh',
                        'ci' => 'f CFA',
                        'other' => '€',
                    ],
                    'options' => [
                        '<li class="list-group-item">Mise en forme d\'une page de présentation</li>',
                        '<li class="list-group-item">1 page de gallerie d\'images avec légendes</li>',
                        '<li class="list-group-item">Page de mentions légales</li>',
                        '<li class="list-group-item">1 formulaire de contact</li>',
                        '<li class="list-group-item">1 carte google si désirée</li>',
                    ],
                    'additional_options' => [
                        '<li class="list-group-item text-muted">Rédaction du contenu</li>',
                        '<li class="list-group-item text-muted">Mise à jour de votre contenu</li>',
                        '<li class="list-group-item text-muted">Ajout de langue</li>',
                        '<li class="list-group-item text-muted">Formulaire avancé (calendrier, demande de réservation, etc.)</li>',
                        '<li class="list-group-item text-muted">Système de gestion de la galérie</li>',
                        '<li class="list-group-item text-muted">Autres fonctionalités sur étude</li>',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Portfolio Pro',
                    'amount' => [
                        'ma' => 3600,
                        'ci' => 190000,
                        'other' => 360,
                    ],
                    'unity' => [
                        'ma' => 'Dh',
                        'ci' => 'f CFA',
                        'other' => '€',
                    ],
                    'options' => [
                        '<li class="list-group-item">Mise en forme d\'une page de présentation</li>',
                        '<li class="list-group-item">4 pages de gallerie d\'images filtrable avec détail par référence</li>',
                        '<li class="list-group-item">Page de mentions légales</li>',
                        '<li class="list-group-item">1 formulaire de contact</li>',
                        '<li class="list-group-item">1 carte google si désirée</li>',
                    ],
                    'additional_options' => [
                        '<li class="list-group-item text-muted">Rédaction du contenu</li>',
                        '<li class="list-group-item text-muted">Mise à jour de votre contenu</li>',
                        '<li class="list-group-item text-muted">Ajout de langue</li>',
                        '<li class="list-group-item text-muted">Formulaire avancé (calendrier, demande de réservation, etc.)</li>',
                        '<li class="list-group-item text-muted">Système de gestion de la galérie</li>',
                        '<li class="list-group-item text-muted">Autres fonctionalités sur étude</li>',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Portfolio High',
                    'amount' => [
                        'ma' => 7200,
                        'ci' => 380000,
                        'other' => 720,
                    ],
                    'unity' => [
                        'ma' => 'Dh',
                        'ci' => 'f CFA',
                        'other' => '€',
                    ],
                    'options' => [
                        '<li class="list-group-item">Mise en forme d\'une page de présentation</li>',
                        '<li class="list-group-item">10 pages de gallerie d\'images filtrable avec détail par référence</li>',
                        '<li class="list-group-item">Page de mentions légales</li>',
                        '<li class="list-group-item">1 formulaire de contact</li>',
                        '<li class="list-group-item">1 carte google si désirée</li>',
                    ],
                    'additional_options' => [
                        '<li class="list-group-item text-muted">Rédaction du contenu</li>',
                        '<li class="list-group-item text-muted">Mise à jour de votre contenu</li>',
                        '<li class="list-group-item text-muted">Ajout de langue</li>',
                        '<li class="list-group-item text-muted">Formulaire avancé (calendrier, demande de réservation, etc.)</li>',
                        '<li class="list-group-item text-muted">Système de gestion de la galérie</li>',
                        '<li class="list-group-item text-muted">Autres fonctionalités sur étude</li>',
                    ],
                    'url' => '',
                ],
            ],
            'e_commerce' => [
                [
                    'title' => 'Mini Boutique',
                    'amount' => [
                        'ma' => 9900,
                        'ci' => 580000,
                        'other' => 1100,
                    ],
                    'unity' => [
                        'ma' => 'Dh',
                        'ci' => 'f CFA',
                        'other' => '€',
                    ],
                    'options' => [
                        '<li class="list-group-item">Mise en forme de vos contenus pour 3 pages</li>',
                        '<li class="list-group-item">Votre zone boutique</li>',
                        '<li class="list-group-item">Page de mentions légales</li>',
                        '<li class="list-group-item">Outils complet de gestion de produits &amp; commande</li>',
                        '<li class="list-group-item">Espace utlisateur</li>',
                        '<li class="list-group-item">1 formulaire de contact + 1 carte google si désirée</li>',
                    ],
                    'additional_options' => [
                        '<li class="list-group-item text-muted">Rédaction du contenu</li>',
                        '<li class="list-group-item text-muted">Mise à jour de votre contenu</li>',
                        '<li class="list-group-item text-muted">Ajout de langue</li>',
                        '<li class="list-group-item text-muted">Formulaire avancé (calendrier, demande de réservation, etc.)</li>',
                        '<li class="list-group-item text-muted">Autres fonctionalités sur étude</li>',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Boutique Pro',
                    'amount' => [
                        'ma' => 19500,
                        'ci' => 1060000,
                        'other' => 2500,
                    ],
                    'unity' => [
                        'ma' => 'Dh',
                        'ci' => 'f CFA',
                        'other' => '€',
                    ],
                    'options' => [
                        '<li class="list-group-item">Mise en forme de vos contenus pour 8 pages</li>',
                        '<li class="list-group-item">Votre zone boutique</li>',
                        '<li class="list-group-item">Page de mentions légales</li>',
                        '<li class="list-group-item">Outils complet de gestion de produits &amp; commande</li>',
                        '<li class="list-group-item">Espace utlisateur</li>',
                        '<li class="list-group-item">1 formulaire de contact + 1 carte google si désirée</li>',
                    ],
                    'additional_options' => [
                        '<li class="list-group-item text-muted">Rédaction du contenu</li>',
                        '<li class="list-group-item text-muted">Mise à jour de votre contenu</li>',
                        '<li class="list-group-item text-muted">Ajout de langue</li>',
                        '<li class="list-group-item text-muted">Formulaire avancé (calendrier, demande de réservation, etc.)</li>',
                        '<li class="list-group-item text-muted">Autres fonctionalités sur étude</li>',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Boutique Prenium',
                    'amount' => [
                        'ma' => 39500,
                        'ci' => 2300000,
                        'other' => 4900,
                    ],
                    'unity' => [
                        'ma' => 'Dh',
                        'ci' => 'f CFA',
                        'other' => '€',
                    ],
                    'options' => [
                        '<li class="list-group-item">Mise en forme de vos contenus pour 15 pages</li>',
                        '<li class="list-group-item">Votre zone boutique</li>',
                        '<li class="list-group-item">Page de mentions légales</li>',
                        '<li class="list-group-item">Outils complet de gestion de produits &amp; commande</li>',
                        '<li class="list-group-item">Espace utlisateur</li>',
                        '<li class="list-group-item">1 formulaire de contact + 1 carte google si désirée</li>',
                    ],
                    'additional_options' => [
                        '<li class="list-group-item text-muted">Rédaction du contenu</li>',
                        '<li class="list-group-item text-muted">Mise à jour de votre contenu</li>',
                        '<li class="list-group-item text-muted">Ajout de langue</li>',
                        '<li class="list-group-item text-muted">Formulaire avancé (calendrier, demande de réservation, etc.)</li>',
                        '<li class="list-group-item text-muted">Autres fonctionalités sur étude</li>',
                    ],
                    'url' => '',
                ],
            ],
            'catalog' => [
                [
                    'title' => 'Mini Catalogue',
                    'amount' => [
                        'ma' => 8500,
                        'ci' => 510000,
                        'other' => 820,
                    ],
                    'unity' => [
                        'ma' => 'Dh',
                        'ci' => 'f CFA',
                        'other' => '€',
                    ],
                    'options' => [
                        '<li class="list-group-item">Mise en forme de vos contenus pour 3 pages</li>',
                        '<li class="list-group-item">Votre zone Catalogue + Page de mentions légales</li>',
                        '<li class="list-group-item">Outils complet de gestion de produits &amp; commande</li>',
                        '<li class="list-group-item">1 formulaire de demande de devis</li>',
                        '<li class="list-group-item">1 formulaire de contact + 1 carte google si désirée</li>',
                    ],
                    'additional_options' => [
                        '<li class="list-group-item text-muted">Rédaction du contenu</li>',
                        '<li class="list-group-item text-muted">Mise à jour de votre contenu</li>',
                        '<li class="list-group-item text-muted">Ajout de langue</li>',
                        '<li class="list-group-item text-muted">Formulaire avancé (calendrier, demande de réservation, etc.)</li>',
                        '<li class="list-group-item text-muted">Autres fonctionalités sur étude</li>',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Catalogue Pro',
                    'amount' => [
                        'ma' => 16500,
                        'ci' => 1020000,
                        'other' => 1650,
                    ],
                    'unity' => [
                        'ma' => 'Dh',
                        'ci' => 'f CFA',
                        'other' => '€',
                    ],
                    'options' => [
                        '<li class="list-group-item">Mise en forme de vos contenus pour 8 pages</li>',
                        '<li class="list-group-item">Votre zone Catalogue + Page de mentions légales</li>',
                        '<li class="list-group-item">Outils complet de gestion de produits &amp; commande</li>',
                        '<li class="list-group-item">1 formulaire de demande de devis</li>',
                        '<li class="list-group-item">1 formulaire de contact + 1 carte google si désirée</li>',
                    ],
                    'additional_options' => [
                        '<li class="list-group-item text-muted">Rédaction du contenu</li>',
                        '<li class="list-group-item text-muted">Mise à jour de votre contenu</li>',
                        '<li class="list-group-item text-muted">Ajout de langue</li>',
                        '<li class="list-group-item text-muted">Formulaire avancé (calendrier, demande de réservation, etc.)</li>',
                        '<li class="list-group-item text-muted">Autres fonctionalités sur étude</li>',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Catalogue Premium',
                    'amount' => [
                        'ma' => 33400,
                        'ci' => 2050000,
                        'other' => 3350,
                    ],
                    'unity' => [
                        'ma' => 'Dh',
                        'ci' => 'f CFA',
                        'other' => '€',
                    ],
                    'options' => [
                        '<li class="list-group-item">Mise en forme de vos contenus pour 15 pages</li>',
                        '<li class="list-group-item">Votre zone Catalogue + Page de mentions légales</li>',
                        '<li class="list-group-item">Outils complet de gestion de produits &amp; commande</li>',
                        '<li class="list-group-item">1 formulaire de demande de devis</li>',
                        '<li class="list-group-item">1 formulaire de contact + 1 carte google si désirée</li>',
                    ],
                    'additional_options' => [
                        '<li class="list-group-item text-muted">Rédaction du contenu</li>',
                        '<li class="list-group-item text-muted">Mise à jour de votre contenu</li>',
                        '<li class="list-group-item text-muted">Ajout de langue</li>',
                        '<li class="list-group-item text-muted">Formulaire avancé (calendrier, demande de réservation, etc.)</li>',
                        '<li class="list-group-item text-muted">Autres fonctionalités sur étude</li>',
                    ],
                    'url' => '',
                ],
            ],
        ],
    ],

    'en' => [
        'home' => [
            [
                'title' => 'Pack Web Stater',
                'amount' => 1200,
                'unity' => 'Dh',
                'options' => [
                    '<li class="list-group-item">Hébergement</li>',
                    '<li class="list-group-item">Nom de domaine</li>',
                    '<li class="list-group-item">Thème responsive design</li>',
                    '<li class="list-group-item">Développement de 2 pages</li>',
                    '<li class="list-group-item">Rédaction de contenu</li>',
                    '<li class="list-group-item">Optimisation SEO</li>',
                    '<li class="list-group-item">Mise à jour du contenu</li>',
                    '<li class="list-group-item">Ajout de médias</li>',
                    '<li class="list-group-item">Maintenance du site</li>',
                    '<li class="list-group-item">Optimisation de contenu</li>',
                ],
                'url' => '',
            ],
            [
                'title' => 'Pack E-Com Mini',
                'amount' => 5500,
                'unity' => 'Dh',
                'options' => [
                    '<li class="list-group-item">Hébergement</li>',
                    '<li class="list-group-item">Nom de domaine</li>',
                    '<li class="list-group-item">Thème responsive design</li>',
                    '<li class="list-group-item">Développement de 4 pages</li>',
                    '<li class="list-group-item">Rédaction de contenu</li>',
                    '<li class="list-group-item">Optimisation SEO</li>',
                    '<li class="list-group-item">Mise à jour du contenu</li>',
                    '<li class="list-group-item">Ajout de médias</li>',
                    '<li class="list-group-item">Maintenance du site</li>',
                    '<li class="list-group-item">Optimisation de contenu</li>',
                ],
                'url' => '',
            ],
            [
                'title' => 'Pack Web Pro',
                'amount' => 3400,
                'unity' => 'Dh',
                'options' => [
                    '<li class="list-group-item">Hébergement</li>',
                    '<li class="list-group-item">Nom de domaine</li>',
                    '<li class="list-group-item">Thème responsive design</li>',
                    '<li class="list-group-item">Développement de 2 pages</li>',
                    '<li class="list-group-item">Rédaction de contenu</li>',
                    '<li class="list-group-item">Optimisation SEO</li>',
                    '<li class="list-group-item">Mise à jour du contenu</li>',
                    '<li class="list-group-item">Ajout de médias</li>',
                    '<li class="list-group-item">Maintenance du site</li>',
                    '<li class="list-group-item">Optimisation de contenu</li>',
                ],
                'url' => '',
            ],
        ],
        'prices' => [
            'showcase' => [
                [
                    'title' => 'Vitrine Starter',
                    'amount' => [
                        'ma' => 1500,
                        'ci' => 85000,
                        'other' => 150,
                    ],
                    'unity' => [
                        'ma' => 'Dh',
                        'ci' => 'f CFA',
                        'other' => '€',
                    ],
                    'options' => [
                        '<li class="list-group-item">Mise en forme d\'une single page</li>',
                        '<li class="list-group-item">Page de mentions légales</li>',
                        '<li class="list-group-item">1 formulaire de contact</li>',
                        '<li class="list-group-item">1 carte google si désirée</li>',
                    ],
                    'additional_options' => [
                        '<li class="list-group-item text-muted">Rédaction du contenu</li>',
                        '<li class="list-group-item text-muted">Mise à jour de votre contenu</li>',
                        '<li class="list-group-item text-muted">Ajout de langue</li>',
                        '<li class="list-group-item text-muted">Formulaire avancé (calendrier, demande de réservation, etc.)</li>',
                        '<li class="list-group-item text-muted">Autres fonctionalités sur étude</li>',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Vitrine Pro',
                    'amount' => [
                        'ma' => 3000,
                        'ci' => 170000,
                        'other' => 350,
                    ],
                    'unity' => [
                        'ma' => 'Dh',
                        'ci' => 'f CFA',
                        'other' => '€',
                    ],
                    'options' => [
                        '<li class="list-group-item">Mise en forme de 4 pages</li>',
                        '<li class="list-group-item">Page de mentions légales</li>',
                        '<li class="list-group-item">1 formulaire de contact</li>',
                        '<li class="list-group-item">1 carte google si désirée</li>',
                    ],
                    'additional_options' => [
                        '<li class="list-group-item text-muted">Rédaction du contenu</li>',
                        '<li class="list-group-item text-muted">Mise à jour de votre contenu</li>',
                        '<li class="list-group-item text-muted">Ajout de langue</li>',
                        '<li class="list-group-item text-muted">Formulaire avancé (calendrier, demande de réservation, etc.)</li>',
                        '<li class="list-group-item text-muted">Autres fonctionalités sur étude</li>',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Vitrine High',
                    'amount' => [
                        'ma' => 6000,
                        'ci' => 340000,
                        'other' => 700,
                    ],
                    'unity' => [
                        'ma' => 'Dh',
                        'ci' => 'f CFA',
                        'other' => '€',
                    ],
                    'options' => [
                        '<li class="list-group-item">Mise en forme de 10 pages</li>',
                        '<li class="list-group-item">Page de mentions légales</li>',
                        '<li class="list-group-item">1 formulaire de contact</li>',
                        '<li class="list-group-item">1 carte google si désirée</li>',
                    ],
                    'additional_options' => [
                        '<li class="list-group-item text-muted">Rédaction du contenu</li>',
                        '<li class="list-group-item text-muted">Mise à jour de votre contenu</li>',
                        '<li class="list-group-item text-muted">Ajout de langue</li>',
                        '<li class="list-group-item text-muted">Formulaire avancé (calendrier, demande de réservation, etc.)</li>',
                        '<li class="list-group-item text-muted">Autres fonctionalités sur étude</li>',
                    ],
                    'url' => '',
                ],
            ],
            'portfolio' => [
                [
                    'title' => 'Portfolio Starter',
                    'amount' => [
                        'ma' => 1800,
                        'ci' => 95000,
                        'other' => 180,
                    ],
                    'unity' => [
                        'ma' => 'Dh',
                        'ci' => 'f CFA',
                        'other' => '€',
                    ],
                    'options' => [
                        '<li class="list-group-item">Mise en forme d\'une page de présentation</li>',
                        '<li class="list-group-item">1 page de gallerie d\'images avec légendes</li>',
                        '<li class="list-group-item">Page de mentions légales</li>',
                        '<li class="list-group-item">1 formulaire de contact</li>',
                        '<li class="list-group-item">1 carte google si désirée</li>',
                    ],
                    'additional_options' => [
                        '<li class="list-group-item text-muted">Rédaction du contenu</li>',
                        '<li class="list-group-item text-muted">Mise à jour de votre contenu</li>',
                        '<li class="list-group-item text-muted">Ajout de langue</li>',
                        '<li class="list-group-item text-muted">Formulaire avancé (calendrier, demande de réservation, etc.)</li>',
                        '<li class="list-group-item text-muted">Système de gestion de la galérie</li>',
                        '<li class="list-group-item text-muted">Autres fonctionalités sur étude</li>',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Portfolio Pro',
                    'amount' => [
                        'ma' => 3600,
                        'ci' => 190000,
                        'other' => 360,
                    ],
                    'unity' => [
                        'ma' => 'Dh',
                        'ci' => 'f CFA',
                        'other' => '€',
                    ],
                    'options' => [
                        '<li class="list-group-item">Mise en forme d\'une page de présentation</li>',
                        '<li class="list-group-item">4 pages de gallerie d\'images filtrable avec détail par référence</li>',
                        '<li class="list-group-item">Page de mentions légales</li>',
                        '<li class="list-group-item">1 formulaire de contact</li>',
                        '<li class="list-group-item">1 carte google si désirée</li>',
                    ],
                    'additional_options' => [
                        '<li class="list-group-item text-muted">Rédaction du contenu</li>',
                        '<li class="list-group-item text-muted">Mise à jour de votre contenu</li>',
                        '<li class="list-group-item text-muted">Ajout de langue</li>',
                        '<li class="list-group-item text-muted">Formulaire avancé (calendrier, demande de réservation, etc.)</li>',
                        '<li class="list-group-item text-muted">Système de gestion de la galérie</li>',
                        '<li class="list-group-item text-muted">Autres fonctionalités sur étude</li>',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Portfolio High',
                    'amount' => [
                        'ma' => 7200,
                        'ci' => 380000,
                        'other' => 720,
                    ],
                    'unity' => [
                        'ma' => 'Dh',
                        'ci' => 'f CFA',
                        'other' => '€',
                    ],
                    'options' => [
                        '<li class="list-group-item">Mise en forme d\'une page de présentation</li>',
                        '<li class="list-group-item">10 pages de gallerie d\'images filtrable avec détail par référence</li>',
                        '<li class="list-group-item">Page de mentions légales</li>',
                        '<li class="list-group-item">1 formulaire de contact</li>',
                        '<li class="list-group-item">1 carte google si désirée</li>',
                    ],
                    'additional_options' => [
                        '<li class="list-group-item text-muted">Rédaction du contenu</li>',
                        '<li class="list-group-item text-muted">Mise à jour de votre contenu</li>',
                        '<li class="list-group-item text-muted">Ajout de langue</li>',
                        '<li class="list-group-item text-muted">Formulaire avancé (calendrier, demande de réservation, etc.)</li>',
                        '<li class="list-group-item text-muted">Système de gestion de la galérie</li>',
                        '<li class="list-group-item text-muted">Autres fonctionalités sur étude</li>',
                    ],
                    'url' => '',
                ],
            ],
            'e_commerce' => [
                [
                    'title' => 'Mini Boutique',
                    'amount' => [
                        'ma' => 9900,
                        'ci' => 580000,
                        'other' => 1100,
                    ],
                    'unity' => [
                        'ma' => 'Dh',
                        'ci' => 'f CFA',
                        'other' => '€',
                    ],
                    'options' => [
                        '<li class="list-group-item">Mise en forme de vos contenus pour 3 pages</li>',
                        '<li class="list-group-item">Votre zone boutique</li>',
                        '<li class="list-group-item">Page de mentions légales</li>',
                        '<li class="list-group-item">Outils complet de gestion de produits &amp; commande</li>',
                        '<li class="list-group-item">Espace utlisateur</li>',
                        '<li class="list-group-item">1 formulaire de contact + 1 carte google si désirée</li>',
                    ],
                    'additional_options' => [
                        '<li class="list-group-item text-muted">Rédaction du contenu</li>',
                        '<li class="list-group-item text-muted">Mise à jour de votre contenu</li>',
                        '<li class="list-group-item text-muted">Ajout de langue</li>',
                        '<li class="list-group-item text-muted">Formulaire avancé (calendrier, demande de réservation, etc.)</li>',
                        '<li class="list-group-item text-muted">Autres fonctionalités sur étude</li>',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Boutique Pro',
                    'amount' => [
                        'ma' => 19500,
                        'ci' => 1060000,
                        'other' => 2500,
                    ],
                    'unity' => [
                        'ma' => 'Dh',
                        'ci' => 'f CFA',
                        'other' => '€',
                    ],
                    'options' => [
                        '<li class="list-group-item">Mise en forme de vos contenus pour 8 pages</li>',
                        '<li class="list-group-item">Votre zone boutique</li>',
                        '<li class="list-group-item">Page de mentions légales</li>',
                        '<li class="list-group-item">Outils complet de gestion de produits &amp; commande</li>',
                        '<li class="list-group-item">Espace utlisateur</li>',
                        '<li class="list-group-item">1 formulaire de contact + 1 carte google si désirée</li>',
                    ],
                    'additional_options' => [
                        '<li class="list-group-item text-muted">Rédaction du contenu</li>',
                        '<li class="list-group-item text-muted">Mise à jour de votre contenu</li>',
                        '<li class="list-group-item text-muted">Ajout de langue</li>',
                        '<li class="list-group-item text-muted">Formulaire avancé (calendrier, demande de réservation, etc.)</li>',
                        '<li class="list-group-item text-muted">Autres fonctionalités sur étude</li>',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Boutique Prenium',
                    'amount' => [
                        'ma' => 39500,
                        'ci' => 2300000,
                        'other' => 4900,
                    ],
                    'unity' => [
                        'ma' => 'Dh',
                        'ci' => 'f CFA',
                        'other' => '€',
                    ],
                    'options' => [
                        '<li class="list-group-item">Mise en forme de vos contenus pour 15 pages</li>',
                        '<li class="list-group-item">Votre zone boutique</li>',
                        '<li class="list-group-item">Page de mentions légales</li>',
                        '<li class="list-group-item">Outils complet de gestion de produits &amp; commande</li>',
                        '<li class="list-group-item">Espace utlisateur</li>',
                        '<li class="list-group-item">1 formulaire de contact + 1 carte google si désirée</li>',
                    ],
                    'additional_options' => [
                        '<li class="list-group-item text-muted">Rédaction du contenu</li>',
                        '<li class="list-group-item text-muted">Mise à jour de votre contenu</li>',
                        '<li class="list-group-item text-muted">Ajout de langue</li>',
                        '<li class="list-group-item text-muted">Formulaire avancé (calendrier, demande de réservation, etc.)</li>',
                        '<li class="list-group-item text-muted">Autres fonctionalités sur étude</li>',
                    ],
                    'url' => '',
                ],
            ],
            'catalog' => [
                [
                    'title' => 'Mini Catalogue',
                    'amount' => [
                        'ma' => 8500,
                        'ci' => 510000,
                        'other' => 820,
                    ],
                    'unity' => [
                        'ma' => 'Dh',
                        'ci' => 'f CFA',
                        'other' => '€',
                    ],
                    'options' => [
                        '<li class="list-group-item">Mise en forme de vos contenus pour 3 pages</li>',
                        '<li class="list-group-item">Votre zone Catalogue + Page de mentions légales</li>',
                        '<li class="list-group-item">Outils complet de gestion de produits &amp; commande</li>',
                        '<li class="list-group-item">1 formulaire de demande de devis</li>',
                        '<li class="list-group-item">1 formulaire de contact + 1 carte google si désirée</li>',
                    ],
                    'additional_options' => [
                        '<li class="list-group-item text-muted">Rédaction du contenu</li>',
                        '<li class="list-group-item text-muted">Mise à jour de votre contenu</li>',
                        '<li class="list-group-item text-muted">Ajout de langue</li>',
                        '<li class="list-group-item text-muted">Formulaire avancé (calendrier, demande de réservation, etc.)</li>',
                        '<li class="list-group-item text-muted">Autres fonctionalités sur étude</li>',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Catalogue Pro',
                    'amount' => [
                        'ma' => 16500,
                        'ci' => 1020000,
                        'other' => 1650,
                    ],
                    'unity' => [
                        'ma' => 'Dh',
                        'ci' => 'f CFA',
                        'other' => '€',
                    ],
                    'options' => [
                        '<li class="list-group-item">Mise en forme de vos contenus pour 8 pages</li>',
                        '<li class="list-group-item">Votre zone Catalogue + Page de mentions légales</li>',
                        '<li class="list-group-item">Outils complet de gestion de produits &amp; commande</li>',
                        '<li class="list-group-item">1 formulaire de demande de devis</li>',
                        '<li class="list-group-item">1 formulaire de contact + 1 carte google si désirée</li>',
                    ],
                    'additional_options' => [
                        '<li class="list-group-item text-muted">Rédaction du contenu</li>',
                        '<li class="list-group-item text-muted">Mise à jour de votre contenu</li>',
                        '<li class="list-group-item text-muted">Ajout de langue</li>',
                        '<li class="list-group-item text-muted">Formulaire avancé (calendrier, demande de réservation, etc.)</li>',
                        '<li class="list-group-item text-muted">Autres fonctionalités sur étude</li>',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Catalogue Premium',
                    'amount' => [
                        'ma' => 33400,
                        'ci' => 2050000,
                        'other' => 3350,
                    ],
                    'unity' => [
                        'ma' => 'Dh',
                        'ci' => 'f CFA',
                        'other' => '€',
                    ],
                    'options' => [
                        '<li class="list-group-item">Mise en forme de vos contenus pour 15 pages</li>',
                        '<li class="list-group-item">Votre zone Catalogue + Page de mentions légales</li>',
                        '<li class="list-group-item">Outils complet de gestion de produits &amp; commande</li>',
                        '<li class="list-group-item">1 formulaire de demande de devis</li>',
                        '<li class="list-group-item">1 formulaire de contact + 1 carte google si désirée</li>',
                    ],
                    'additional_options' => [
                        '<li class="list-group-item text-muted">Rédaction du contenu</li>',
                        '<li class="list-group-item text-muted">Mise à jour de votre contenu</li>',
                        '<li class="list-group-item text-muted">Ajout de langue</li>',
                        '<li class="list-group-item text-muted">Formulaire avancé (calendrier, demande de réservation, etc.)</li>',
                        '<li class="list-group-item text-muted">Autres fonctionalités sur étude</li>',
                    ],
                    'url' => '',
                ],
            ],
        ],
    ],
];