<?php

return [
    'fr' => [
        'home' => [
            [
                'title' => 'Pack Web Stater',
                'amount' => 1200,
                'unity' => 'Dh',
                'options' => [
                    '<li class="list-group-item">Hébergement</li>',
                    '<li class="list-group-item">Nom de domaine</li>',
                    '<li class="list-group-item">Thème responsive design</li>',
                    '<li class="list-group-item">Développement de 2 pages</li>',
                    '<li class="list-group-item">Rédaction de contenu</li>',
                    '<li class="list-group-item">Optimisation SEO</li>',
                    '<li class="list-group-item">Mise à jour du contenu</li>',
                    '<li class="list-group-item">Ajout de médias</li>',
                    '<li class="list-group-item">Maintenance du site</li>',
                    '<li class="list-group-item">Optimisation de contenu</li>',
                ],
                'url' => '',
            ],
            [
                'title' => 'Pack E-Com Mini',
                'amount' => 5500,
                'unity' => 'Dh',
                'options' => [
                    '<li class="list-group-item">Hébergement</li>',
                    '<li class="list-group-item">Nom de domaine</li>',
                    '<li class="list-group-item">Thème responsive design</li>',
                    '<li class="list-group-item">Développement de 4 pages</li>',
                    '<li class="list-group-item">Rédaction de contenu</li>',
                    '<li class="list-group-item">Optimisation SEO</li>',
                    '<li class="list-group-item">Mise à jour du contenu</li>',
                    '<li class="list-group-item">Ajout de médias</li>',
                    '<li class="list-group-item">Maintenance du site</li>',
                    '<li class="list-group-item">Optimisation de contenu</li>',
                ],
                'url' => '',
            ],
            [
                'title' => 'Pack Web Pro',
                'amount' => 3400,
                'unity' => 'Dh',
                'options' => [
                    '<li class="list-group-item">Hébergement</li>',
                    '<li class="list-group-item">Nom de domaine</li>',
                    '<li class="list-group-item">Thème responsive design</li>',
                    '<li class="list-group-item">Développement de 2 pages</li>',
                    '<li class="list-group-item">Rédaction de contenu</li>',
                    '<li class="list-group-item">Optimisation SEO</li>',
                    '<li class="list-group-item">Mise à jour du contenu</li>',
                    '<li class="list-group-item">Ajout de médias</li>',
                    '<li class="list-group-item">Maintenance du site</li>',
                    '<li class="list-group-item">Optimisation de contenu</li>',
                ],
                'url' => '',
            ],
        ],
        'prices' => [
            'showcase' => [
                [
                    'title' => 'Price name',
                    'amount' => 99,
                    'unity' => 'Dh',
                    'options' => [
                        'Option 0',
                        'Option 1',
                        'Option 2',
                        'Option 3',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Price name',
                    'amount' => 99,
                    'unity' => 'Dh',
                    'options' => [
                        'Option 0',
                        'Option 1',
                        'Option 2',
                        'Option 3',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Price name',
                    'amount' => 99,
                    'unity' => 'Dh',
                    'options' => [
                        'Option 0',
                        'Option 1',
                        'Option 2',
                        'Option 3',
                    ],
                    'url' => '',
                ],
            ],
            'portfolio' => [
                [
                    'title' => 'Price name',
                    'amount' => 99,
                    'unity' => 'Dh',
                    'options' => [
                        'Option 0',
                        'Option 1',
                        'Option 2',
                        'Option 3',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Price name',
                    'amount' => 99,
                    'unity' => 'Dh',
                    'options' => [
                        'Option 0',
                        'Option 1',
                        'Option 2',
                        'Option 3',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Price name',
                    'amount' => 99,
                    'unity' => 'Dh',
                    'options' => [
                        'Option 0',
                        'Option 1',
                        'Option 2',
                        'Option 3',
                    ],
                    'url' => '',
                ],
            ],
            'e_commerce' => [
                [
                    'title' => 'Price name',
                    'amount' => 99,
                    'unity' => 'Dh',
                    'options' => [
                        'Option 0',
                        'Option 1',
                        'Option 2',
                        'Option 3',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Price name',
                    'amount' => 99,
                    'unity' => 'Dh',
                    'options' => [
                        'Option 0',
                        'Option 1',
                        'Option 2',
                        'Option 3',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Price name',
                    'amount' => 99,
                    'unity' => 'Dh',
                    'options' => [
                        'Option 0',
                        'Option 1',
                        'Option 2',
                        'Option 3',
                    ],
                    'url' => '',
                ],
            ],
            'catalog' => [
                [
                    'title' => 'Price name',
                    'amount' => 99,
                    'unity' => 'Dh',
                    'options' => [
                        'Option 0',
                        'Option 1',
                        'Option 2',
                        'Option 3',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Price name',
                    'amount' => 99,
                    'unity' => 'Dh',
                    'options' => [
                        'Option 0',
                        'Option 1',
                        'Option 2',
                        'Option 3',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Price name',
                    'amount' => 99,
                    'unity' => 'Dh',
                    'options' => [
                        'Option 0',
                        'Option 1',
                        'Option 2',
                        'Option 3',
                    ],
                    'url' => '',
                ],
            ],
        ],
    ],

    'en' => [
        'home' => [
            [
                'title' => 'Price name',
                'amount' => 99,
                'unity' => 'Dh',
                'options' => [
                    'Option 0',
                    'Option 1',
                    'Option 2',
                    'Option 3',
                ],
                'url' => '',
            ],
            [
                'title' => 'Price name',
                'amount' => 99,
                'unity' => 'Dh',
                'options' => [
                    'Option 0',
                    'Option 1',
                    'Option 2',
                    'Option 3',
                ],
                'url' => '',
            ],
            [
                'title' => 'Price name',
                'amount' => 99,
                'unity' => 'Dh',
                'options' => [
                    'Option 0',
                    'Option 1',
                    'Option 2',
                    'Option 3',
                ],
                'url' => '',
            ],
        ],
        'prices' => [
            'showcase' => [
                [
                    'title' => 'Price name',
                    'amount' => 99,
                    'unity' => 'Dh',
                    'options' => [
                        'Option 0',
                        'Option 1',
                        'Option 2',
                        'Option 3',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Price name',
                    'amount' => 99,
                    'unity' => 'Dh',
                    'options' => [
                        'Option 0',
                        'Option 1',
                        'Option 2',
                        'Option 3',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Price name',
                    'amount' => 99,
                    'unity' => 'Dh',
                    'options' => [
                        'Option 0',
                        'Option 1',
                        'Option 2',
                        'Option 3',
                    ],
                    'url' => '',
                ],
            ],
            'portfolio' => [
                [
                    'title' => 'Price name',
                    'amount' => 99,
                    'unity' => 'Dh',
                    'options' => [
                        'Option 0',
                        'Option 1',
                        'Option 2',
                        'Option 3',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Price name',
                    'amount' => 99,
                    'unity' => 'Dh',
                    'options' => [
                        'Option 0',
                        'Option 1',
                        'Option 2',
                        'Option 3',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Price name',
                    'amount' => 99,
                    'unity' => 'Dh',
                    'options' => [
                        'Option 0',
                        'Option 1',
                        'Option 2',
                        'Option 3',
                    ],
                    'url' => '',
                ],
            ],
            'e_commerce' => [
                [
                    'title' => 'Price name',
                    'amount' => 99,
                    'unity' => 'Dh',
                    'options' => [
                        'Option 0',
                        'Option 1',
                        'Option 2',
                        'Option 3',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Price name',
                    'amount' => 99,
                    'unity' => 'Dh',
                    'options' => [
                        'Option 0',
                        'Option 1',
                        'Option 2',
                        'Option 3',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Price name',
                    'amount' => 99,
                    'unity' => 'Dh',
                    'options' => [
                        'Option 0',
                        'Option 1',
                        'Option 2',
                        'Option 3',
                    ],
                    'url' => '',
                ],
            ],
            'catalog' => [
                [
                    'title' => 'Price name',
                    'amount' => 99,
                    'unity' => 'Dh',
                    'options' => [
                        'Option 0',
                        'Option 1',
                        'Option 2',
                        'Option 3',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Price name',
                    'amount' => 99,
                    'unity' => 'Dh',
                    'options' => [
                        'Option 0',
                        'Option 1',
                        'Option 2',
                        'Option 3',
                    ],
                    'url' => '',
                ],
                [
                    'title' => 'Price name',
                    'amount' => 99,
                    'unity' => 'Dh',
                    'options' => [
                        'Option 0',
                        'Option 1',
                        'Option 2',
                        'Option 3',
                    ],
                    'url' => '',
                ],
            ],
        ],
    ],
];